### ISSUE TITLE
Paging support fordelta commands

### ISSUE THREAD

**Issue by timayabi2020** [microsoftgraph/msgraph-sdk-powershell#1876]
There is need to add paging support for delta commands.  This is because the response body for delta requests that returns more than one results page contains "@odata.nextLink".

<img width="381" alt="image" src="https://user-images.githubusercontent.com/10947120/225120524-02a0eef8-abc6-412d-9864-122bca66829e.png">

**Comment by peombwa** [comment]
To fix this, we will need to update the directive at https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/features/2.0/src/readme.graph.md to add `-All` to `Delta` variants as well. `-All` is currently only added to `List` variants.
``` yml
# Directive to update
# Modify generated .cs list cmdlets.
  - from: source-file-csharp
    where: $
    transform: >
      if (!$documentPath.match(/generated%2Fcmdlets%2FGet\w*_List\d*.cs/gm))
```
