### ISSUE TITLE
[v2] Review Existing Default Views for Common Entity Types

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#1903]
Existing default views (Format-List) should only have properties that are returned by default. For example, `UserType` is only returned by default in beta and shouldn't be present in v1.0:
``` yml
  - where:
      model-name: ^MicrosoftGraphUser\d*$
    set:
      format-table:
        properties:
          - Id
          - DisplayName
          - Mail
          - UserPrincipalName
          - UserType
```

Other changes to fix:
- [x] https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1839
