### ISSUE TITLE
When connecting to Graph in Azure Automation PowerShell 7.2 with a managed identity, the welcome message is still output even though the -NoWelcome switch is specified.

### ISSUE THREAD

**Issue by lrarbin** [microsoftgraph/msgraph-sdk-powershell#2547]
**Describe the bug**
When connecting to Graph in Azure Automation PowerShell 7.2 with a managed identity, the welcome message is still output even though the -NoWelcome switch is specified.

``
$umiGraphAccess = Get-AutomationVariable -Name 'umiGraphAccess'
``
``
$graphcon = Connect-MgGraph -NoWelcome -Identity -ClientId $umiGraphAccess
``

```
    ClientId:
    TenantId:
    Scopes: {TeamSettings.ReadWrite.All, ChannelSettings.Read.All, Directory.ReadWrite.All, Sites.ReadWrite.All…}
    AuthType: ManagedIdentity
    TokenCredentialType: ManagedIdentity
    CertificateThumbprint: 
    CertificateSubjectName: 
    Account: 
    AppName: 
    ContextScope: Process
    Certificate: 
    PSHostVersion: 7.2.0
    ManagedIdentityId:
    ClientSecret: 
    Environment: Global
```

**To Reproduce**
- Execute on Azure Automation PowerShell 7.2 with a managed identity
```
$umiGraphAccess = Get-AutomationVariable -Name 'umiGraphAccess'
$graphcon = Connect-MgGraph -NoWelcome -Identity -ClientId $umiGraphAccess
```
- View Output in Azure Automation job.

**Expected behavior**
Nothing should be output to the Output Window in Azure Automation PowerShell 7.2 from the Connect-MgGraph cmdlet if the -NoWelcome switch is used.

**Debug Output**
Cannot get this easily from Azure Automation

**Module Version**
> Please run `Get-Module Microsoft.Graph*` after cmdlet execution and paste the output below.
> If a module cannot be installed or imported, please run `Get-Module -ListAvailable` and paste the output.

In the available modules
```
Name IsGlobal Version SizeInBytes Activity
Microsoft.Graph.Applications                    False 2.12.0      3899749    0
Microsoft.Graph.Authentication                  False 2.12.0      6370566    0
Microsoft.Graph.Files                           False 2.12.0     29037842    0
Microsoft.Graph.Groups                          False 2.12.0      5296678    0
Microsoft.Graph.Identity.DirectoryManagement    False 2.12.0      4148344    0
Microsoft.Graph.Sites                           False 2.12.0     16650651    0
Microsoft.Graph.Teams                           False 2.12.0     10951496    0
Microsoft.Graph.Users                           False 2.12.0      3645180    0
```
In the script
```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.0                Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-Mg…

Script     2.12.0                Microsoft.Graph.Identity.Directory… {Confirm-MgContactMemberGroup, Confirm-MgContactMe…
```

**Environment Data**
```
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![MicrosoftAzureAutomation](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/8376969/9befa5bc-dcf1-459b-8576-078981328bcb)

**Additional context**
> Add any other context about the problem here.
