### ISSUE TITLE
Duplicated operaionId

### ISSUE THREAD

**Issue by dinowang** [microsoftgraph/msgraph-sdk-powershell#2843]
### Describe the bug

Multiple Open API spec has duplicated operaionId

For example:
https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/v1.0/Users.yml

```yaml
  '/users/{user-id}/photo':
    get:
      tags:
        - users.profilePhoto
      summary: Get photo from users
      description: The user's profile photo. Read-only.
      operationId: user_GetPhoto
      parameters:
        - name: user-id
```

```yaml
  '/users/{user-id}/photos/{profilePhoto-id}':
    get:
      tags:
        - users.profilePhoto
      summary: Get photos from users
      description: The collection of the user's profile photos in different sizes. Read-only.
      operationId: user_GetPhoto
      parameters:
        - name: user-id
```

When user import Open API spec into product/service. Like Azure API Management will cause conflict
<img width="1631" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/3980212/b46ba21a-9bf1-4cbb-8546-d0699e13257c">

### Expected behavior

OperationId should unique.

### How to reproduce

1.  Create Azure API Management service
2. Click API, create API from defination
3. Paste Open API spec URL, fill the form then press Create

<img width="1678" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/3980212/12cabb8f-6839-4270-9920-d86a9b705690">

### SDK Version

v1.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>
