### ISSUE TITLE
OpenAPIDoc issue causing cmdlet breakage: DeviceManagement.Functions

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/msgraph-sdk-powershell#760]
The listed success response for `/deviceManagement/virtualEndpoint/auditEvents/microsoft.graph.getAuditActivityTypes()` invoked by 
`Get-MgDeviceManagementVirtualEndpointAuditEventAuditActivityType` has an incorrect response structure. 
The API returns:-
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#Collection(Edm.String)",
    "value": [
        "*"
    ]
}
```
While the OpenAPIDoc lists the response as:-
```
  responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  nullable: true
```
instead of the structure shown below, where the array of strings is contained in an object with a value property. 
```
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                   type: array
                   items:
                     type: string
                     nullable: true
```
The original metadata:-
![image](https://user-images.githubusercontent.com/1641829/125642920-ab7ac2f9-5b27-41c9-8496-8068c4be9184.png)

Affected Cmdlets in `Microsoft.Graph.DeviceManagement.Functions` :-
- Get-MgDeviceManagementVirtualEndpointAuditEventAuditActivityType 
- Get-MgDeviceManagementVirtualEndpointEffectivePermission 
[AB#10214](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10214)

Related to [#80](https://github.com/microsoftgraph/msgraph-metadata/issues/80)
