### ISSUE TITLE
Update-MgUserPlanner Should Support `If-match` header

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-powershell#822]
Using `Update-MgUserPlanner` to [update a plannerUser object](https://docs.microsoft.com/en-us/graph/api/planneruser-update?view=graph-rest-beta&tabs=http) fails with the following error:

``` powershell
PS C:\> Select-MgProfile beta
PS C:\> Update-MgUserPlanner -UserId $env:App_User_Id -Debug

DEBUG: URLCreated: https://graph.microsoft.com/beta/users/{user-id}/planner
Content-Type: application/json
{
}
Update-MgUserPlanner_UpdateExpanded: The If-Match header must be specified for this kind of request.
...
```

Customers do not currently have an option for specifying request headers. The [OpenAPI spec states](https://swagger.io/specification/#header-object) that a document should explicitly declare request headers in an operation's `parameters` object with an `in: header` e.g.,
``` yml
  /planner:
    patch:
      tags:
        - planner.planner
      summary: Update planerUser object.
      operationId: planner.planner_UpdatePlanner
      parameters:
        - name: If-match
          in: header
          schema:
            type: string
```
